import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.scss"
import { SITE_NAME } from '@/app/constants/seo.constants'
import { Toaster } from 'sonner'
import Navbar from '../components/Admin/Navbar'

const inter = Inter({
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`
	},
	description: "Generated by create next app",
}
export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (

		<div className="wrapper">
			<div className="flex w-full">
				<div className="w-full">
					<Toaster position="bottom-right" richColors />
					{children}
				</div>
			</div>
		</div>

	)
}
